# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.177.0/containers/dotnet/.devcontainer/base.Dockerfile

FROM mcr.microsoft.com/devcontainers/dotnet:9.0

RUN dotnet workload update
