// <auto-generated />
using System.Text.Json.Nodes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StixApi.Persistance;

#nullable disable

namespace StixApi.Migrations
{
    [DbContext(typeof(StixDbContext))]
    [Migration("20250331172253_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StixApi.Persistance.Models.Vulnerability", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("Id");

                    b.Property<JsonObject>("Value")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.ToTable("Vulnerability", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
